SUBROUTINE DEALLOCATE_ARRAY()
USE PROBLEM_DEF
IMPLICIT NONE

 CALL DEALLOCATE_PROBLEM_DEF
 CALL DEALLOCATE_FLUID_PROPERTIES
 CALL DEALLOCATE_LS_DATA
 CALL DEALLOCATE_VOF_DATA
 CALL DEALLOCATE_DUMMY_DATA
 CALL DEALLOCATE_IBM_DATA
 CALL DEALLOCATE_VORTEX_DATA

END SUBROUTINE

SUBROUTINE DEALLOCATE_PROBLEM_DEF
USE PROBLEM_DEF
IMPLICIT NONE

  DEALLOCATE(X,Y,Z)
  
END SUBROUTINE

SUBROUTINE DEALLOCATE_FLUID_PROPERTIES
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE

  DEALLOCATE( U,V,W,UH,VH,WH )
  DEALLOCATE(U_OLD,U_TMP,U1,US,US_OLD)
  DEALLOCATE(V_OLD,V_TMP,V1,VS,VS_OLD)
  DEALLOCATE(W_OLD,W_TMP,W1,WS,WS_OLD)
  DEALLOCATE(RHO, RHO_OLD, AMU, AMU_OLD)
  DEALLOCATE(P,P_OLD,P_OLD2,P_TMP,RHS)

END SUBROUTINE

SUBROUTINE DEALLOCATE_LS_DATA
USE PROBLEM_DEF
USE LS_DATA
IMPLICIT NONE

  DEALLOCATE( PHI, PHI_OLD, PHI_TMP, PHI_V, PHI_I )
  DEALLOCATE( NORMAL_X, NORMAL_Y, NORMAL_Z )
  DEALLOCATE( CURV, HEAVY, DELTA, GRAD, SGN )

END SUBROUTINE

SUBROUTINE DEALLOCATE_VOF_DATA
USE PROBLEM_DEF
USE VOF_DATA
IMPLICIT NONE
 
 DEALLOCATE( VOF_X, VOF_Y, VOF_Z )
 DEALLOCATE( VOF_SX, VOF_SY, VOF_SZ )
 DEALLOCATE( VOF, VVOF, VOF_OLD, VOF_I )

END SUBROUTINE

SUBROUTINE DEALLOCATE_DUMMY_DATA
USE PROBLEM_DEF
USE DUMMY_DATA
IMPLICIT NONE

 DEALLOCATE( S0, S1, S2, SS0 ,SS1, SS2 )
 DEALLOCATE( UP,UM,VP,VM,WP,WM )
 DEALLOCATE( A,B,C,F,G,H )
 DEALLOCATE( FP,FM,GP,GM,HP,HM )

END SUBROUTINE

SUBROUTINE DEALLOCATE_IBM_DATA
USE PROBLEM_DEF
USE IBM_DATA
IMPLICIT NONE

 DEALLOCATE( SOLID_PHI, SOLID_VOF )

END SUBROUTINE

SUBROUTINE DEALLOCATE_VORTEX_DATA
USE PROBLEM_DEF
USE VORTEX_DATA
IMPLICIT NONE

 DEALLOCATE( LAMB_X, LAMB_Y, LAMB_Z )
 DEALLOCATE( VOR_X, VOR_Y, VOR_Z )
 DEALLOCATE( LAMB_DIV, Q_CRI, DELTA_CRI, LAM2_CRI )
 DEALLOCATE( FLEX_PROD, ENTROPY, HELICITY )

END SUBROUTINE 



