SUBROUTINE MPLS()
IMPLICIT NONE
 
 CALL MPLS_correction_step
 CALL MPLS_correction_step
 
END SUBROUTINE

SUBROUTINE MPLS_correction_step()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP) :: FS

 CALL HEAVY_F(PHI)
 
 MASS_LS=0.0
 FS=0.0
 
 !$OMP PARALLEL DO
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   NORMAL_X(I,J,K)=0.5*(PHI(I+1,J,K)-PHI(I-1,J,K))/DX
   NORMAL_Y(I,J,K)=0.5*(PHI(I,J+1,K)-PHI(I,J-1,K))/DY
   NORMAL_Z(I,J,K)=0.5*(PHI(I,J,K+1)-PHI(I,J,K-1))/DZ 
   GRAD(I,J,K) = DSQRT(NORMAL_X(I,J,K)**2+NORMAL_Y(I,J,K)**2+NORMAL_Z(I,J,K)**2)
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO
 
 !$OMP PARALLEL DO REDUCTION(+:MASS_LS,FS)
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X  
    MASS_LS = MASS_LS + HEAVY(I,J,K)*(HEAVY(I,J,K) + RATIO_RHO*(1.0-HEAVY(I,J,K)))
    FS = FS + DELTA(I,J,K)**2*GRAD(I,J,K)*( 2.0_DP*(1.0_DP-RATIO_RHO)*HEAVY(I,J,K)+RATIO_RHO )
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 FS=(IMASS_LS-MASS_LS)/FS
 
 !$OMP PARALLEL DO
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   PHI(I,J,K) = PHI(I,J,K) + FS*DELTA(I,J,K)*GRAD(I,J,K)
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO

 CALL BC_LS()
 
END SUBROUTINE
