SUBROUTINE PLOT()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA, ONLY : PHI
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP) :: cpu_PLOT
CHARACTER(2) :: MET,GRI,NUM
character(20) :: nam

 IF(ABS(TIME-PLOT_INT*TIME_TO_PLOT)<DT)THEN
   CONTINUE
 ELSE
   RETURN
 END IF
 
 cpu_PLOT = -wtime ( )

 WRITE(MET,'(I2.2)')ITER_CNT
 WRITE(GRI,'(I2.2)')GRID_CNT
 WRITE(NUM,'(I2.2)')PLOT_INT
 
 CALL PLOT_VTK(MET,GRI,NUM)
  
 PLOT_INT = PLOT_INT+1

 cpu_PLOT = cpu_PLOT + wtime ( )

 CPU_COST = CPU_COST - cpu_PLOT

END SUBROUTINE PLOT



