SUBROUTINE PLOT_VTK(MET,GRI,NUM)
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
USE FLUID_PROPERTIES, ONLY : UH,VH,WH
use VORTEX_DATA
IMPLICIT NONE
INTEGER :: I,J,K
CHARACTER(2) :: NUM,MET,GRI

  
  OPEN(UNIT=99,FILE=trim(NAME_OF_PROB)//MET//'_'//GRI//'_'//NUM//'.vtk')
  
  !CALL LS_CENTRAL(PHI)
  !CALL CELL_FACE_VELOCITY()
 
  WRITE(99,'(A)')"# vtk DataFile Version 3.0"
  write(99,'(A)')"vtk TEST"
  WRITE(99,'(A)')"ASCII"
  WRITE(99,'(A)')"DATASET STRUCTURED_POINTS"
  WRITE(99,'(A,3I6)')"DIMENSIONS",NODE_X,NODE_Y,NODE_Z
  WRITE(99,'(A,3ES15.4)')"SPACING",DX,DY,DZ
  WRITE(99,'(A,3ES15.4)')"ORIGIN",XSTART,YSTART,ZSTART
  WRITE(99,'(A,I)')"POINT_DATA",NODE_X*NODE_Y*NODE_Z
  

  CALL PLOT_VTK_SCALAR(99,"PHI",PHI)
  !CALL PLOT_VTK_SCALAR(99,"Curvature",CURV)
  !CALL PLOT_VTK_VECTOR(99,"Velocity",UH,VH,WH)
  
  IF( VORTEX_DYNAMICS .EQ. 1 )THEN
    CALL VORTEX_IDENTIFICATION
    CALL PLOT_VTK_VECTOR(99,"Vorticity",Vor_x,Vor_y,Vor_z)
    CALL PLOT_VTK_VECTOR(99,"Lamb",Lamb_x,Lamb_y,Lamb_z)
    CALL PLOT_VTK_SCALAR(99,"Q_criterion",Q_CRI)
	CALL PLOT_VTK_SCALAR(99,"Lam2_criterion",Lam2_CRI)
	CALL PLOT_VTK_SCALAR(99,"Delta_criterion",Delta_CRI)
	CALL PLOT_VTK_SCALAR(99,"Lamb_divergence",LAMB_DIV)
	CALL PLOT_VTK_SCALAR(99,"Helicity",HELICITY)
  ENDIF
  
  CLOSE(99)
  

END SUBROUTINE

SUBROUTINE PLOT_VTK_SCALAR(ID,NAME,X)
USE PROBLEM_DEF, ONLY : NODE_X,NODE_Y,NODE_Z
USE PRECISION
IMPLICIT NONE
INTEGER :: I,J,K,ID
CHARACTER(*) :: NAME
REAL(DP),DIMENSION(-2:NODE_X+3,-2:NODE_Y+3,-2:NODE_Z+3) :: X

  WRITE(ID,'(A)')"SCALARS "//NAME//" FLOAT"
  WRITE(ID,'(A)')"LOOKUP_TABLE DEFAULT"
  
  CALL ARRAY_FILTER(X)
  
  DO K = 1, NODE_Z
  DO J = 1, NODE_Y
  DO I = 1, NODE_X
	WRITE(ID,'(ES15.4)')X(I,J,K)
  ENDDO
  ENDDO
  ENDDO
  
  write(ID,*)""
  
END SUBROUTINE

SUBROUTINE PLOT_VTK_VECTOR(ID,NAME,X,Y,Z)
USE PROBLEM_DEF, ONLY : NODE_X,NODE_Y,NODE_Z
USE PRECISION
IMPLICIT NONE
INTEGER :: I,J,K,ID
CHARACTER(*) :: NAME
REAL(DP),DIMENSION(-2:NODE_X+3,-2:NODE_Y+3,-2:NODE_Z+3) :: X,Y,Z

  WRITE(ID,'(A)')"VECTORS "//NAME//" FLOAT"
  
  CALL ARRAY_FILTER(X)
  CALL ARRAY_FILTER(Y)
  CALL ARRAY_FILTER(Z)
  
  DO K = 1, NODE_Z
  DO J = 1, NODE_Y
  DO I = 1, NODE_X
	WRITE(ID,'(3ES15.4)')X(I,J,K),Y(I,J,K),Z(I,J,K)
  ENDDO
  ENDDO
  ENDDO
  
  write(ID,*)""
  

END SUBROUTINE


SUBROUTINE ARRAY_FILTER(X)
USE PROBLEM_DEF, ONLY : NODE_X,NODE_Y,NODE_Z
USE PRECISION
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP),DIMENSION(-2:NODE_X+3,-2:NODE_Y+3,-2:NODE_Z+3) :: X

 !$OMP PARALLEL DO
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
	IF(ABS(X(I,J,K))<EPS)X(I,J,K)=0.0_dp
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO
 
 
END SUBROUTINE