SUBROUTINE AMURHO()
USE PRECISION
USE FLUID_PROPERTIES
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J

 IF( INTERFACE_METHOD == 0 )THEN
 	
  CALL HEAVY_F(PHI)
 	
 	!$OMP PARALLEL DO
  DO J = 1, NODE_Y
  DO I = 1, NODE_X
    RHO(I,J) = HEAVY(I,J) + RATIO_RHO*(1.0-HEAVY(I,J))
    AMU(I,J) = HEAVY(I,J) + RATIO_AMU*(1.0-HEAVY(I,J))
  END DO
  END DO
 	!$OMP END PARALLEL DO
 	
 ELSE
 	
 	!$OMP PARALLEL DO
  DO J = 1, NODE_Y
  DO I = 1, NODE_X
    RHO(I,J) = VOF(I,J) + RATIO_RHO*(1.0-VOF(I,J))
    AMU(I,J) = VOF(I,J) + RATIO_AMU*(1.0-VOF(I,J))
  END DO
  END DO
 	!$OMP END PARALLEL DO
 	
 END IF
 
  CALL BC3D(RHO)
  CALL BC3D(AMU)

END SUBROUTINE