SUBROUTINE FIND_CURVATURE(TARGET)
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE DUMMY_DATA
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP),DIMENSION(-2:NODE_X+3,-2:NODE_Y+3) :: TARGET
REAL(DP) :: FX,FY,FXX,FYY,FXY

 !$OMP PARALLEL DO PRIVATE(FX,FY,FXX,FYY,FXY)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
 
    fx=0.5_DP/dx*(TARGET(i+1,j)-TARGET(i-1,j))
    fy=0.5_DP/dy*(TARGET(i,j+1)-TARGET(i,j-1))  

    fxx=1.0_DP/dx**2*(TARGET(i+1,j)-2.0_DP*TARGET(i,j)+TARGET(i-1,j))
    fyy=1.0_DP/dy**2*(TARGET(i,j+1)-2.0_DP*TARGET(i,j)+TARGET(i,j-1))

    fxy=0.25_DP/(dx*dy)*(TARGET(i+1,j+1)-TARGET(i+1,j-1) &
          -              TARGET(i-1,j+1)+TARGET(i-1,j-1))

    CURV(i,j)=(fxx*fy**2+fyy*fx**2-2.0_DP*fxy*fx*fy) / (fx**2+fy**2+EPS)**1.5 

    NORMAL_X(I,J) = FX !/ DSQRT(FX**2+FY**2+EPS)
    NORMAL_Y(I,J) = FY !/ DSQRT(FX**2+FY**2+EPS)
 
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 CALL BC3D(CURV)
 CALL BC3D(NORMAL_X)
 CALL BC3D(NORMAL_Y)

END SUBROUTINE

SUBROUTINE FIND_CURVATURE_CCD(TARGET)
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE DUMMY_DATA
IMPLICIT NONE
INTEGER :: I,J
REAL(DP),DIMENSION(-2:NODE_X+3,-2:NODE_Y+3) :: TARGET
REAL(DP) :: FX,FY,FXX,FYY,FXY

 !$OMP PARALLEL DO
 DO J = 1, NODE_Y
 	CALL CCD(NODE_X,Dx,TARGET(1:NODE_X,J),A(1:NODE_X,J),F(1:NODE_X,J))
 END DO
 !$OMP END PARALLEL DO
 
 !$OMP PARALLEL DO
 DO I = 1, NODE_X
 	CALL CCD(NODE_Y,DY,TARGET(I,1:NODE_Y),B(I,1:NODE_Y),G(I,1:NODE_Y))
 END DO
 !$OMP END PARALLEL DO
 
 ! FX_Y
 !$OMP PARALLEL DO
 DO I = 1, NODE_X
 	CALL CCD(NODE_Y,DY,A(I,1:NODE_Y),VP(I,1:NODE_Y),VM(I,1:NODE_Y))
 END DO
 !$OMP END PARALLEL DO
 

 !$OMP PARALLEL DO PRIVATE(FX,FY,FXX,FYY,FXY)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
 
    fx=A(I,J)
    fy=B(I,J)       

    fxx=F(I,J)
    fyy=G(I,J)

    fxy=VP(I,J)

    
    CURV(i,j)=(fxx*fy**2+fyy*fx**2-2.0_DP*fxy*fx*fy) / (fx**2+fy**2+EPS)**1.5 

    NORMAL_X(I,J) = FX !/ DSQRT(FX**2+FY**2+EPS)
    NORMAL_Y(I,J) = FY !/ DSQRT(FX**2+FY**2+EPS)
 
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 CALL BC3D(CURV)
 CALL BC3D(NORMAL_X)
 CALL BC3D(NORMAL_Y)

END SUBROUTINE