SUBROUTINE SETUP()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
USE IBM_DATA
IMPLICIT NONE
INTEGER :: I,J,K,II,JJ,KK
REAL(DP) :: XS,YS,ZS
REAL(DP) :: IMF, B, DEL, DELX
REAL(DP) :: OH

XSTART = 0.0_DP
XEND   = 1.0_DP

YSTART = 0.0_DP
YEND   = 1.0_DP

XL = XEND-XSTART
YL = YEND-YSTART
UNIT_GRID = 32*2**ITER_CNT
UNIT_GRID2 = 20

NODE_X = UNIT_GRID * (XEND-XSTART)
NODE_Y = UNIT_GRID * (YEND-YSTART)

DX = 1.0_DP / REAL(UNIT_GRID,KIND=DP)
DY = DX

DT = 0.002_DP / 256.0_DP
RDT = 0.25_DP*DX
INTERFACE_WIDTH = 1.5*DX

PRESS_OMEGA = 1.5_DP
PRESS_MAX_IT = 1000000

REC_MASS = 0
PLOT_INT = 0

! Tolerance of convervence

TOL_P = 1.0E-9_DP
TOL_M = 1.0E-5_DP

! Enviornment Parameters

RHO_L = 762.0_DP
RHO_G = 1.29_DP

MU_L = 2.13E-3_DP
MU_G = 1.846E-5_DP

GRAVITY = 9.81
SURFACE_TENSION = 0.078_DP

! Characteristic Value

CHAR_LENGTH = 168.0e-6
CHAR_VELOCITY = 1.5707_DP
CHAR_TIME = CHAR_LENGTH / CHAR_VELOCITY

TIME_TO_STOP = 1.0
TIME_TO_PLOT = -1

! Dimensionless Parameters

 RE = RHO_L * CHAR_VELOCITY * CHAR_LENGTH / MU_L
 WE = RHO_L * CHAR_VELOCITY**2 * CHAR_LENGTH / SURFACE_TENSION
 FR = CHAR_VELOCITY / DSQRT(GRAVITY*CHAR_LENGTH)
 RATIO_RHO = RHO_G / RHO_L
 RATIO_AMU = MU_G / MU_L

 RATIO_RHO = 1.0_DP
 RATIO_AMU = 1.0_DP
 Re   = 42792.0_DP    ! Case A
 !!Re   = 121033.0_DP   ! Case B
 Fr   = 1.0_dp	
 WE   = 0.68_DP
 
 
! Numerical Setup

INTERFACE_METHOD = 4
IBM_SOLVER = 0
VEL_BC = 0
ST_FORCE = 0
G_FORCE = 1

LS_SOLVER = 10
VOF_SOLVER = 0

SOLID_MOTION = 0
VELOCITY_INTERPOLATION = 1

 CALL TO_FILE
 
! Data Initialization

CALL ALLOCATE_ARRAY

X(0) = XSTART
X(NODE_X+1) = XEND

Y(0) = YSTART
Y(NODE_Y+1) = YEND

!$OMP PARALLEL DO
DO I = 1, NODE_X
 X(I) = XSTART + (REAL(I,KIND=DP)-0.5_DP)*DX
END DO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO
DO J = 1, NODE_Y
 Y(J) = YSTART + (REAL(J,KIND=DP)-0.5_DP)*DY
END DO
!$OMP END PARALLEL DO

 CALL READ_DATA
 IF(READ_OPER==1)GOTO 10

IMF = 0.06_DP ! impact factor
B = 1.2_DP   ! distance of center in z direction
DEL = 1.0_DP ! ratio of diameter

DELX = IMF*(1.0+del)*0.5

!$OMP PARALLEL DO PRIVATE(XS,YS,ZS,II,JJ,KK)
DO J = 1, NODE_Y
DO I = 1, NODE_X

  U(I,J) = 0.0_DP
  V(I,J) = 0.0_DP
  P(I,J) = 0.0_DP
  VOF(I,J) = 0.0_DP
  
  ! DO II = 1, UNIT_GRID2
  ! DO JJ = 1, UNIT_GRID2
  
  !   XS = 0.5_DP*(X(I-1)+X(I)) + REAL(II,KIND=DP)*DX/REAL(UNIT_GRID2,KIND=DP)
  !   YS = 0.5_DP*(Y(J-1)+Y(J)) + REAL(JJ,KIND=DP)*DY/REAL(UNIT_GRID2,KIND=DP) 

  !   if( (xs-0.5)**2+(ys-0.75)**2 <= 0.15**2 )VOF(i,j) = vof(i,j) + 1.0
   
	 !  if( abs(xs-0.5) <= 0.025 .and. ys< 0.8 .and. (xs-0.5)**2+(ys-0.75)**2 <= 0.15**2 )VOF(i,j) = vof(i,j) - 1.0

  ! END DO
  ! END DO
  
  ! VOF(I,J) = VOF(I,J) / REAL(UNIT_GRID2**2,KIND=DP)
  
  XS = X(I)
  YS = Y(J)
  
  phi(i,j) = -dsqrt((xs-0.5)**2+(ys-0.75)**2)+0.15
  
  PHI_i(I,J) = PHI(I,J)
  
  ! U(i,j) = -(ys-0.5)
  ! UH(I,J) = U(I,J)
  
  ! V(i,j) =  (xs-0.5) 
  ! VH(I,J) = V(I,J)
  
END DO
END DO
!$OMP END PARALLEL DO

 CALL BC3D(PHI)
 CALL BC3D(VOF)
 CALL BC3D(U)
 CALL BC3D(V)
 CALL BC3D(UH)
 CALL BC3D(VH)
 
 ! CALL LS_REDISTANCE(PHI,0)

 CALL PLOT
 
 TIME=ITER*DT
 
10  CALL AMURHO
 CALL STORE_DATA 
 CALL SOLVE_NS
 CALL STORE_DATA
 CALL FIND_MASS
 CALL CPU_START_REC()

END SUBROUTINE

