SUBROUTINE ALLOCATE_ARRAY()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
USE IBM_DATA
USE DUMMY_DATA

ALLOCATE(X(0:NODE_X+1),Y(0:NODE_Y+1))

ALLOCATE( U(-2:NODE_X+3,-2:NODE_Y+3), UH(-2:NODE_X+3,-2:NODE_Y+3), U_OLD(-2:NODE_X+3,-2:NODE_Y+3), U_TMP(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( U1(-2:NODE_X+3,-2:NODE_Y+3), US(-2:NODE_X+3,-2:NODE_Y+3), US_OLD(-2:NODE_X+3,-2:NODE_Y+3) )

ALLOCATE( V(-2:NODE_X+3,-2:NODE_Y+3), VH(-2:NODE_X+3,-2:NODE_Y+3), V_OLD(-2:NODE_X+3,-2:NODE_Y+3), V_TMP(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( V1(-2:NODE_X+3,-2:NODE_Y+3), VS(-2:NODE_X+3,-2:NODE_Y+3), VS_OLD(-2:NODE_X+3,-2:NODE_Y+3) )

ALLOCATE( RHO(-2:NODE_X+3,-2:NODE_Y+3), RHO_OLD(-2:NODE_X+3,-2:NODE_Y+3), AMU(-2:NODE_X+3,-2:NODE_Y+3), AMU_OLD(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( P(-2:NODE_X+3,-2:NODE_Y+3), P_OLD(-2:NODE_X+3,-2:NODE_Y+3), RHS(-2:NODE_X+3,-2:NODE_Y+3) )

ALLOCATE(PHI(-2:NODE_X+3,-2:NODE_Y+3), PHI_OLD(-2:NODE_X+3,-2:NODE_Y+3), PHI_TMP(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( NORMAL_X(-2:NODE_X+3,-2:NODE_Y+3), NORMAL_Y(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( CURV(-2:NODE_X+3,-2:NODE_Y+3), GRAD(-2:NODE_X+3,-2:NODE_Y+3), HEAVY(-2:NODE_X+3,-2:NODE_Y+3), SGN(-2:NODE_X+3,-2:NODE_Y+3), DELTA(-2:NODE_X+3,-2:NODE_Y+3))

ALLOCATE( VOF(-2:NODE_X+3,-2:NODE_Y+3), VOF_OLD(-2:NODE_X+3,-2:NODE_Y+3), VOF_X(-2:NODE_X+3,-2:NODE_Y+3), VOF_Y(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE( VOF_SX(-2:NODE_X+3,-2:NODE_Y+3), VOF_SY(-2:NODE_X+3,-2:NODE_Y+3) )

ALLOCATE(SOLID_PHI(-2:NODE_X+3,-2:NODE_Y+3), SOLID_VOF(-2:NODE_X+3,-2:NODE_Y+3),PHI_V(-2:NODE_X+3,-2:NODE_Y+3) )

ALLOCATE(S0(-2:NODE_X+3,-2:NODE_Y+3), S1(-2:NODE_X+3,-2:NODE_Y+3), S2(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE(SS0(-2:NODE_X+3,-2:NODE_Y+3), SS1(-2:NODE_X+3,-2:NODE_Y+3), SS2(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE(UP(-2:NODE_X+3,-2:NODE_Y+3), UM(-2:NODE_X+3,-2:NODE_Y+3), VP(-2:NODE_X+3,-2:NODE_Y+3), VM(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE(A(-2:NODE_X+3,-2:NODE_Y+3), B(-2:NODE_X+3,-2:NODE_Y+3), C(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE(F(-2:NODE_X+3,-2:NODE_Y+3), G(-2:NODE_X+3,-2:NODE_Y+3) )
ALLOCATE(FP(-2:NODE_X+3,-2:NODE_Y+3), FM(-2:NODE_X+3,-2:NODE_Y+3), GP(-2:NODE_X+3,-2:NODE_Y+3), GM(-2:NODE_X+3,-2:NODE_Y+3))

ALLOCATE( PHI_I(-2:NODE_X+3,-2:NODE_Y+3), VOF_I(-2:NODE_X+3,-2:NODE_Y+3) )

END SUBROUTINE

SUBROUTINE FREE_ARRAY()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
USE IBM_DATA
USE DUMMY_DATA

DEALLOCATE( X,Y )
DEALLOCATE( U, UH, U_OLD, U_TMP, U1, US, US_OLD )
DEALLOCATE( V, VH, V_OLD, V_TMP, V1, VS, VS_OLD )
DEALLOCATE( RHO, RHO_OLD, AMU, AMU_OLD )
DEALLOCATE( P, P_OLD, RHS )
DEALLOCATE( PHI, PHI_OLD, PHI_TMP, PHI_V, PHI_I )
DEALLOCATE( NORMAL_X,NORMAL_Y )
DEALLOCATE( CURV, HEAVY, DELTA, GRAD, SGN )
DEALLOCATE( VOF, VOF_OLD, VOF_I )
DEALLOCATE( VOF_X, VOF_Y )
DEALLOCATE( VOF_SX,VOF_SY )
DEALLOCATE( SOLID_PHI, SOLID_VOF )
DEALLOCATE( S0,S1,S2,SS0,SS1,SS2 )
DEALLOCATE( UP,UM,VP,VM )
DEALLOCATE( A,B,C,F,G,FP,FM,GP,GM )


END SUBROUTINE
