MODULE PRECISION
IMPLICIT NONE
SAVE
INTEGER,PARAMETER :: DP = SELECTED_REAL_KIND(15)
REAL(DP),PARAMETER :: EPS = 1.0E-12_DP
REAL(DP),PARAMETER :: PI = 3.14159265358979323846264338327950288419_DP
END MODULE PRECISION

MODULE PROBLEM_DEF
USE PRECISION
IMPLICIT NONE
SAVE
INTEGER :: INTERFACE_METHOD, IBM_SOLVER, VEL_BC, ST_FORCE, G_FORCE
INTEGER :: NODE_X, NODE_Y, UNIT_GRID, UNIT_GRID2
INTEGER :: ITER, REC_MASS, PLOT_INT, ITER_CNT, METHOD_CNT
INTEGER :: PRESS_MAX_IT, READ_OPER
REAL(DP),ALLOCATABLE,DIMENSION(:) :: X,Y
REAL(DP) :: XSTART, XEND, YSTART, YEND, XL, YL
REAL(DP) :: L2_U, L2_V, LINF_U, LINF_V, LINF_P, DIV, TOL_P, TOL_M
REAL(DP) :: DX,DY,DT,RDT
REAL(DP) :: TIME,TIME_TO_STOP,TIME_TO_PLOT
REAL(DP) :: RATIO_AMU, RATIO_RHO
REAL(DP) :: CHAR_LENGTH, CHAR_VELOCITY, CHAR_TIME
REAL(DP) :: WE, FR, RE
REAL(DP) :: RHO_L,RHO_G,MU_L,MU_G, SURFACE_TENSION,GRAVITY
REAL(DP) :: PRESS_OMEGA, cpu_cost, TE, TS
END MODULE PROBLEM_DEF

MODULE FLUID_PROPERTIES
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: U, UH, U_OLD, U_TMP, U1, US, US_OLD
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: V, VH, V_OLD, V_TMP, V1, VS, VS_OLD
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: RHO, RHO_OLD, AMU, AMU_OLD
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: P, P_OLD, RHS
END MODULE FLUID_PROPERTIES

MODULE LS_DATA
USE PRECISION
IMPLICIT NONE
SAVE
INTEGER :: LS_SOLVER
REAL(DP) :: INTERFACE_WIDTH, IMASS_LS, MASS_LS, RED_STOP, IVOL_LS, VOL_LS
REAL(DP) :: EM_LS, EM_LS_A, EI_LS
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: PHI, PHI_OLD, PHI_TMP, PHI_V, PHI_I
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: NORMAL_X,NORMAL_Y
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: CURV, HEAVY, DELTA, GRAD, SGN
END MODULE LS_DATA

MODULE VOF_DATA
USE PRECISION
IMPLICIT NONE
SAVE
INTEGER  :: VOF_SOLVER
REAL(DP) :: IMASS_VOF, MASS_VOF, IVOL_VOF, VOL_VOF
REAL(DP) :: EM_VOF, EM_VOF_A, EI_VOF
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: VOF, VOF_OLD, VOF_I
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: VOF_X, VOF_Y
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: VOF_SX,VOF_SY
END MODULE VOF_DATA

MODULE IBM_DATA
USE PRECISION
IMPLICIT NONE
SAVE
INTEGER :: SOLID_MOTION, VELOCITY_INTERPOLATION
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: SOLID_PHI, SOLID_VOF
REAL(DP) :: FORCE_X, FORCE_Y, FORCE_X_OLD, FORCE_Y_OLD
REAL(DP) :: TORQUE_X, TORQUE_Y, TORQUE_X_OLD, TORQUE_Y_OLD
REAL(DP) :: SOLID_X, SOLID_Y,  SOLID_X_OLD, SOLID_Y_OLD
REAL(DP) :: SOLID_TX, SOLID_TY, SOLID_TX_OLD, SOLID_TY_OLD
REAL(DP) :: SOLID_U, SOLID_V, SOLID_U_OLD, SOLID_V_OLD
REAL(DP) :: SOLID_WX, SOLID_WY, SOLID_WX_OLD, SOLID_WY_OLD
END MODULE IBM_DATA

MODULE DUMMY_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: S0,S1,S2
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: SS0,SS1,SS2
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: UP,UM,VP,VM
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: A,B,C,F,G
REAL(DP),ALLOCATABLE,DIMENSION(:,:) :: FP,FM,GP,GM
END MODULE DUMMY_DATA