SUBROUTINE FIND_MASS()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J
CHARACTER(2) :: NAME,NAME2,METHOD

 MASS_LS = 0.0_DP
 MASS_VOF = 0.0_DP
 
 VOL_LS = 0.0_DP
 VOL_VOF = 0.0_DP
 
 CALL HEAVY_F(PHI)
 
 !$OMP PARALLEL DO REDUCTION(+:MASS_LS,MASS_VOF,VOL_LS,VOL_VOF)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   VOL_LS = VOL_LS + HEAVY(I,J)
	VOL_VOF = VOL_VOF + VOF(I,J)
 	MASS_LS = MASS_LS + HEAVY(I,J)*(HEAVY(I,J) + RATIO_RHO*(1.0-HEAVY(I,J)))
 MASS_VOF = MASS_VOF + VOF(I,J)*(VOF(I,J) + RATIO_RHO*(1.0-VOF(I,J)))
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 EM_LS_A = EM_LS_A + ABS(1.0-VOL_LS/IVOL_LS)*DT/TIME_TO_STOP
 EM_VOF_A = EM_VOF_A + ABS(1.0-VOL_VOF/IVOL_vof)*DT/TIME_TO_STOP
 
 IF( REC_MASS==0 )THEN
 
    WRITE(NAME2,'(I2.2)')Method_cnt
	WRITE(NAME,'(I2.2)')ITER_CNT
	
 	IMASS_LS = MASS_LS
 	IMASS_VOF = MASS_VOF
	IVOL_LS = VOL_LS
	IVOL_VOF = VOL_VOF
	
 	OPEN(UNIT=11,FILE='MASS LOSS '//NAME2//'_'//NAME//'_.PLT')
	!OPEN(UNIT=11,FILE='MASS LOSS_'//name//'.PLT')
 	! WRITE(11,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '
	WRITE(11,*)'VARIABLES = "t" "area" '

	! OPEN(UNIT=12,FILE='VOL LOSS '//NAME2//'_'//NAME//'_.PLT')
	! !OPEN(UNIT=12,FILE='VOL LOSS_'//name//'.PLT')
 ! 	WRITE(12,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '
	
 	REC_MASS = 1
	EM_LS_A  = 0.0_dp
	EM_VOF_A = 0.0_DP
	
 END IF
 
 WRITE(11,*)TIME,VOL_LS/real(NODE_Y*NODE_x,kind=8)
 ! WRITE(12,*)TIME,(1.0-VOL_LS/IVOL_LS)*100,(1.0-VOL_VOF/IVOL_VOF)*100

END SUBROUTINE