SUBROUTINE STORE_DATA()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J

 !$OMP PARALLEL DO
 DO J = -2, NODE_Y+3
 DO I = -2, NODE_X+3
 
   PHI_OLD(I,J) = PHI(I,J)
   VOF_OLD(I,J) = VOF(I,J)
   
   U_OLD(I,J) = U(I,J)
   V_OLD(I,J) = V(I,J)
   
   US_OLD(I,J) = US(I,J)
   VS_OLD(I,J) = VS(I,J)
   
   RHO_OLD(I,J) = RHO(I,J)
   AMU_OLD(I,J) = AMU(I,J)
 
 END DO
 END DO
 !$OMP END PARALLEL DO

END SUBROUTINE