SUBROUTINE RK3_IX(BTN)
USE DAT
IMPLICIT NONE
INTEGER :: BTN

  !$OMP PARALLEL DO 
  DO I = -2, N+3
	F(I) = IX(I)*U_old(i)+p(I)
  END DO 
  !$OMP END PARALLEL DO 
  
  CALL SORCE(S0,IX,BTN)
  CALL RK3_1(IX)
  CALL BC_R(IX)
  
  !$OMP PARALLEL DO 
  DO I = -2, N+3
	F(I) = IX(I)*U_OLD(i)+p(I)
  END DO 
  !$OMP END PARALLEL DO 
  
  CALL SORCE(S1,IX,BTN)
  CALL RK3_2(IX)
  CALL BC_R(IX)
  
  !$OMP PARALLEL DO 
  DO I = -2, N+3
	F(I) = IX(I)*U_OLD(i)+p(I)
  END DO 
  !$OMP END PARALLEL DO 
  
  CALL SORCE(S2,IX,BTN)
  CALL RK3_3(IX)
  CALL BC_R(IX)
  

END SUBROUTINE
