SUBROUTINE FIND_MASS()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J
CHARACTER(2) :: NAME,NAME2,METHOD

 MASS_LS = 0.0_DP
 VOL_LS = 0.0_DP
 
 CALL HEAVY_F(PHI)
 
 !$OMP PARALLEL DO REDUCTION(+:MASS_LS,VOL_LS)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
    VOL_LS = VOL_LS + HEAVY(I,J)
    MASS_LS = MASS_LS + HEAVY(I,J)*(HEAVY(I,J) + RATIO_RHO*(1.0-HEAVY(I,J)))
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 EM_LS_A = EM_LS_A + ABS(1.0-MASS_LS/IMASS_LS)*DT/TIME_TO_STOP
 EM_MAX = max(EM_MAX,ABS(1.0-MASS_LS/IMASS_LS))

 IF( REC_MASS==0 )THEN
 
    WRITE(NAME,'(I2.2)')ITER_CNT
    WRITE(NAME2,'(I2.2)')GRID_CNT
    
    IMASS_LS = MASS_LS
    IMASS_VOF = MASS_VOF
    IVOL_LS = VOL_LS
    IVOL_VOF = VOL_VOF
    
    OPEN(UNIT=11,FILE='MASS VOL LOSS '//NAME//'_'//NAME2//'_.plt')
    WRITE(11,*)'VARIABLES = "T" "LOSS OF MASS(%)" "LOSS OF VOL(%)" '
    
    REC_MASS = 1
    EM_LS_A  = 0.0_dp
    EM_MAX = 0.0_DP
    
 END IF
 
 WRITE(11,*)TIME,(1.0-MASS_LS/IMASS_LS)*100,(1.0-VOL_LS/IVOL_LS)*100

END SUBROUTINE