SUBROUTINE PLOT()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
USE IBM_DATA
IMPLICIT NONE
INTEGER :: I,J
CHARACTER(2) :: NAME,NAME2,METHOD
REAL(DP) :: CPU_PLOT

  IF(ABS(ITER*DT-PLOT_INT*TIME_TO_PLOT)<DT)THEN
    CONTINUE
  ELSE
    RETURN
  END IF
  
  CPU_PLOT = -wtime ( )

WRITE(NAME,'(I2.2)') PLOT_INT
WRITE(NAME2,'(I2.2)') GRID_CNT
WRITE(METHOD,'(I2.2)')ITER_CNT

!OPEN(UNIT=99,FILE='Nesq_2D_'//METHOD//'_'//NAME2//'_'//NAME//'_.dat',STATUS="UNKNOWN")
!OPEN(UNIT=99,FILE='2D_DamBreak_'//METHOD//'_'//NAME//'.dat',STATUS="UNKNOWN")
OPEN(UNIT=99,FILE=METHOD//'_'//NAME2//'_'//NAME//'.dat',STATUS="UNKNOWN")

WRITE(99,*) 'TITLE = "NUMERICAL SOLUTION" '
SELECT CASE(IBM_SOLVER)
 CASE(0)
    WRITE(99,*) 'VARIABLES =  "X" "Y" "U" "V" "PHI" "VOF" '
 CASE(1)
    WRITE(99,*) 'VARIABLES =  "X" "Y" "U" "V" "PHI" "VOF" "SOLID"'
END SELECT
WRITE(99,*) 'ZONE T= "NUMERICAL", I=',NODE_X+2,', J=',NODE_Y+2,', F= POINT'

SELECT CASE(IBM_SOLVER)
 CASE(0) 
   DO J = 0, NODE_Y+1
   DO I = 0, NODE_X+1
      WRITE(99,'(8E15.6)')X(I),Y(J),U(I,J),V(I,J),PHI(I,J),VOF(I,J)
   END DO
   END DO
 CASE(1)
   DO J = 0, NODE_Y+1
   DO I = 0, NODE_X+1
      WRITE(99,'(9E14.5)')X(I),Y(J),U(I,J),V(I,J),PHI(I,J),VOF(I,J),SOLID_VOF(I,J)
   END DO
   END DO
END SELECT
CLOSE(UNIT=99)

 PLOT_INT=PLOT_INT+1

 cpu_PLOT = cpu_PLOT + wtime()
 CPU_COST = CPU_COST - cpu_PLOT
 
END SUBROUTINE