SUBROUTINE SOLVE_NS()
USE PRECISION
USE FLUID_PROPERTIES
USE LS_DATA
IMPLICIT NONE
INTEGER :: INITER,I,J

  CALL AMURHO()
  CALL HEAVY_F(PHI)
  CALL FIND_CURVATURE_CCD(PHI)

  INITER = 0

  DO
  
    INITER = INITER + 1
  
    !$OMP PARALLEL DO
    DO J = -2, NODE_Y+3
    DO I = -2, NODE_X+3
      U_TMP(I,J) = U(I,J)
      V_TMP(I,J) = V(I,J)
    END DO
    END DO
    !$OMP END PARALLEL DO

    !CALL SECOND_ORDER_UPWIND()
	CALL QUICK
	
    IF( REC_MASS==0 )RETURN
    CALL Adams_Bashforth()

    CALL SOLVE_PRESSURE_POISSON()
    CALL SOLVE_MOMENTUM()
    CALL VELOCITY_BC()
	
    CALL CHECK_CONVERGENCE(INITER)
	
	IF( INITER>3 )EXIT
	
  END DO

END SUBROUTINE

SUBROUTINE CHECK_CONVERGENCE(INITER)
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: INITER,I,J
REAL(DP) :: RES

  CALL FIND_ERROR(L2_U,U,U_TMP,2)
  CALL FIND_ERROR(L2_V,V,V_TMP,2)
 
  CALL FIND_ERROR(LINF_U,U,U_TMP,3)
  CALL FIND_ERROR(LINF_V,V,V_TMP,3)
  
  !IF( L2_U+L2_V< TOL_M )INITER = INITER + 5

 DIV = 0.0_DP
 
 !$omp parallel do REDUCTION(MAX:DIV),PRIVATE(RES)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
 	
    RES=(U(I,J)-U(I-1,J))/DX &
       +(V(I,J)-V(I,J-1))/DY 
       
    DIV = MAX(DIV,ABS(RES))
       
  ENDDO
  ENDDO
  !$omp end parallel do    
  
  
END SUBROUTINE

SUBROUTINE VELOCITY_BC()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES

 CALL BCU(U)
 CALL BCV(V)

END SUBROUTINE

SUBROUTINE SOLVE_MOMENTUM()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J

!$omp parallel do
 DO J = 1, NODE_Y
 DO I = 1, NODE_X-1
   U1(I,J)= -U1(I,J)-2.0*(P(I+1,J)-P(I,J))/(DX*(RHO(I,J)+RHO(I+1,J)))
   U1(I,J)=  U_OLD(I,J)+U1(I,J)*DT
   U(i,j) =  U1(i,j)
 END DO
 END DO
!$omp end parallel do  

!$omp parallel do
 DO J = 1, NODE_Y-1 
 DO I = 1, NODE_X	  
   V1(I,J)= -V1(I,J)-2.0*(P(I,J+1)-P(I,J))/(DY*(RHO(I,J)+RHO(I,J+1)))
   V1(I,J)=  V_OLD(I,J)+V1(I,J)*DT
   V(i,j) =  V1(i,j)
 END DO
 END DO
!$omp end parallel do  

END SUBROUTINE

SUBROUTINE Adams_Bashforth()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J

 !$OMP PARALLEL DO
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
  U1(I,J) = 1.5_DP*US(I,J) - 0.5_DP*US_OLD(I,J)
  V1(I,J) = 1.5_DP*VS(I,J) - 0.5_DP*VS_OLD(I,J)
 END DO
 END DO
 !$OMP END PARALLEL DO

END SUBROUTINE

