SUBROUTINE SOLVE_PRESSURE_POISSON()
IMPLICIT NONE

  CALL RHSP()
  CALL PRESS_POISSON()

END SUBROUTINE

SUBROUTINE RHSP()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J

!$omp parallel do
DO  J=0,NODE_Y+1
  U1(0,J)=0.0_DP
  U1(NODE_X,J)=0.0_DP
ENDDO
!$omp end parallel do

!$omp parallel do
  DO I=0,NODE_X+1
   V1(I,0)=0.0_DP
   V1(I,NODE_Y)=0.0_DP
  ENDDO
!$omp end parallel do


!$omp parallel do
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   RHS(I,J)=(U_OLD(I,J)/DT-U_OLD(I-1,J)/DT-U1(I,J)+U1(I-1,J))/DX &
           +(V_OLD(I,J)/DT-V_OLD(I,J-1)/DT-V1(I,J)+V1(I,J-1))/DY 
  ENDDO
  ENDDO
!$omp end parallel do
  

END SUBROUTINE RHSP

SUBROUTINE PRESS_POISSON()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J,ICOUNTP
REAL(DP) :: RR,RL,RF,RB,CL,CR,CF,CB,CC,DX2,DY2
REAL(DP) :: POLD,PCAL,SUMP

  DX2=DX*DX
  DY2=DY*DY 
   
  ICOUNTP=0
  10 LINF_P = 0.0
  ICOUNTP=ICOUNTP+1

  
!$omp parallel do private(rr,rl,rf,rb,cl,cr,cf,cb,cc,pold,pcal)
DO J=1,NODE_Y
DO I=1,NODE_X

  P_OLD(i,j) = P(i,j)

  RR=0.5*(RHO(I,J)+RHO(I+1,J))
  RL=0.5*(RHO(I,J)+RHO(I-1,J))
  RF=0.5*(RHO(I,J)+RHO(I,J+1))
  RB=0.5*(RHO(I,J)+RHO(I,J-1))
  
  CL=1.0/(DX2*RL)
  CR=1.0/(DX2*RR)
  CF=1.0/(DY2*RF)
  CB=1.0/(DY2*RB)
  
  CC=-(CL+CR+CF+CB)

  IF(I.EQ.1) THEN
    CC=CC+CL
    CL=0.0_DP
  ENDIF

  IF(I.EQ.NODE_X) THEN
    CC=CC+CR
    CR=0.0_DP
  ENDIF

  IF(J.EQ.1) THEN
    CC=CC+CB
    CB=0.0_DP
  ENDIF

  IF(J.EQ.NODE_Y) THEN
    CC=CC+CF
    CF=0.0_DP
  ENDIF
  
  POLD=P(I,J)
  
  PCAL=RHS(I,J)-CL*P(I-1,J)-CR*P(I+1,J) &
               -CB*P(I,J-1)-CF*P(I,J+1)
  PCAL=PCAL/CC

  P(I,J) = PRESS_OMEGA*PCAL+(1.0_DP-PRESS_OMEGA)*POLD

  ENDDO
  ENDDO
!$omp end parallel do

SUMP = 0.0_DP

!$omp parallel do reduction(+:SUMP)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
  SUMP  = SUMP + P(I,J)
 END DO
 END DO
!$OMP END PARALLEL DO

SUMP = SUMP / REAL(NODE_X*NODE_Y,KIND=DP)
  
!$OMP PARALLEL DO reduction(max:LINF_P)
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
  P(I,J) = P(I,J) - SUMP
  LINF_P = max(LINF_P,abs(P(i,j)-P_OLD(i,j)))
 END DO
 END DO
!$OMP END PARALLEL DO

if (mod(ICOUNTP,5000)==0)then 
  WRITE(*,*) "AMAXP=" , LINF_P
end if

IF(LINF_P.LT.TOL_P) GOTO 150
IF(ICOUNTP.GT.PRESS_MAX_IT) GOTO 100
GOTO 10
100 WRITE(2,110) LINF_P
110 FORMAT(3X,'PRESSURE CAN NOT CONVERGENCE, MAX. ERROR IS :',F10.6 &
      /3X,'STOP THE CALCULATION')
STOP
150 CONTINUE

END SUBROUTINE PRESS_POISSON