SUBROUTINE FIND_DAMBREAK_DATA()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA, ONLY : PHI
USE FLUID_PROPERTIES, ONLY : U
IMPLICIT NONE
INTEGER :: I,J,K
real(dp)::loc,LOC_H,FI,FII
character(2) :: grid

  write(grid,'(i2.2)')grid_cnt

  IF( ITER==1 )THEN
    OPEN(UNIT=13,FILE='DamBreak_'//grid//'.plt')
	write(13,*)'variables = "t" "front location" "wetted wall" '
  ENDIF
  
  LOC = 0.0_DP
  
  
  !$OMP PARALLEL DO REDUCTION(MAX:LOC) PRIVATE(FI,FII)
  DO J = 1, NODE_Y
  DO I = 1, NODE_X-1
  
	FI = 1.5_DP*PHI(I,J,1)-0.5_DP*PHI(I,J,2)
	FII = 1.5_DP*PHI(I+1,J,1)-0.5_DP*PHI(I+1,J,2)
	
  	IF(FI*FII<=0.0)THEN
		LOC = MAX(LOC,X(I)+DX*ABS(FI)/(ABS(FI)+ABS(FII)) )
		exit
	ENDIF
	
  ENDDO
  ENDDO
  !$OMP END PARALLEL DO
  
  LOC_H = 0.0_DP

  !$OMP PARALLEL DO REDUCTION(MAX:LOC_H) PRIVATE(FI,FII)
  DO J = 1, NODE_Y
  DO K = 1, NODE_Z-1
   
	FI = 1.5_DP*PHI(1,J,K)-0.5_DP*PHI(2,J,K)
	FII = 1.5_DP*PHI(1,J,K+1)-0.5_DP*PHI(2,J,K+1)
	
  	IF(FI*FII<=0.0)THEN
		LOC_H = MAX(LOC_H,Z(K)+DX*ABS(FI)/(ABS(FI)+ABS(FII)) )
		exit
	ENDIF
	
  ENDDO
  ENDDO
  !$OMP END PARALLEL DO
  
  write(13,*)time,LOC,LOC_H

END SUBROUTINE