SUBROUTINE SETUP()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE LS_DATA
USE VOF_DATA
USE IBM_DATA
IMPLICIT NONE
INTEGER :: I,J,K,II,JJ,KK
REAL(DP) :: XS,YS,ZS
REAL(DP) :: q0

NAME_OF_PROB = "MilkCrown"

XSTART =  -3.0_DP
XEND   =  3.0_DP

YSTART =  -3.0_DP
YEND   =  3.0_DP

ZSTART =  0.0_DP
ZEND   =  3.0_DP

XL = XEND-XSTART
YL = YEND-YSTART
ZL = ZEND-ZSTART

UNIT_GRID = 40!32+32**GRID_CNT
UNIT_GRID2 = 20

NODE_X = UNIT_GRID * (XEND-XSTART)
NODE_Y = UNIT_GRID * (YEND-YSTART)
NODE_Z = UNIT_GRID * (ZEND-ZSTART)

DX = 1.0_DP / REAL(UNIT_GRID,KIND=DP)
DY = DX
DZ = DX

DT = 0.005_DP*DX
RDT = 0.5_DP*DX
INTERFACE_WIDTH = 1.5*DX

PRESS_OMEGA = 0.5_DP
PRESS_MAX_IT = 5000000

REC_MASS = 0
PLOT_INT = 0
ITER = 0
TIME = ITER*DT
FLAG_IS_ON = .FALSE.
 
! Tolerance of convervence

TOL_P = 1.0E-5_DP
TOL_M = 1.0E-8_DP

! Enviornment Parameters

 RHO_L = 1000.0_DP
 RHO_G = 1.25_DP
 
 MU_L  = 1.7E-3
 MU_G  = 1.0E-6
 
 SURFACE_TENSION = 0.05_DP
 GRAVITY = 9.81_DP

! Characteristic Value

 CHAR_LENGTH = 5.33d-3
 CHAR_VELOCITY = 4.0_dp
 CHAR_TIME = CHAR_LENGTH / CHAR_VELOCITY

 TIME_TO_STOP = 8.0_DP
 TIME_TO_PLOT = 0.2
 
! Dimensionless Parameters

 RE = RHO_L * CHAR_VELOCITY * CHAR_LENGTH / MU_L
 WE = RHO_L * CHAR_VELOCITY**2 * CHAR_LENGTH / SURFACE_TENSION
 FR = CHAR_VELOCITY / DSQRT(GRAVITY*CHAR_LENGTH)
 RATIO_RHO = RHO_G / RHO_L
 RATIO_AMU = MU_G / MU_L

!  RATIO_RHO = 0.001
!  RATIO_AMU = 0.01
!  Re   = 474.0_DP   
!  Fr   = 0.64_DP
!  WE   = 1.0_DP
 
! Numerical Setup

!===================
! VOF SOLVER
!
! 1 - THINC/WLIC(LS)
! 2 - THINC/WLIC(VOF)
! 3 - THINC
! 4 - THINC-SW
!
!====================

INTERFACE_METHOD = 2
IBM_SOLVER = 0
NS_SOLVER = 1
VEL_BC = 0
ST_FORCE = 1
G_FORCE = 1

LS_SOLVER = 2
VOF_SOLVER = 1

SOLID_MOTION = 0
VELOCITY_INTERPOLATION = 1
VORTEX_DYNAMICS = 1

 CALL TO_FILE
 
! Data Initialization

 CALL ALLOCATE_ARRAY

X(0) = XSTART
X(NODE_X+1) = XEND

Y(0) = YSTART
Y(NODE_Y+1) = YEND

Z(0) = ZSTART
Z(NODE_Z+1) = ZEND

!$OMP PARALLEL DO
DO I = 1, NODE_X
 X(I) = XSTART + (REAL(I,KIND=DP)-0.5_DP)*DX
END DO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO
DO J = 1, NODE_Y
 Y(J) = YSTART + (REAL(J,KIND=DP)-0.5_DP)*DY
END DO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO
DO K = 1, NODE_Z
 Z(K) = ZSTART + (REAL(K,KIND=DP)-0.5_DP)*DZ
END DO
!$OMP END PARALLEL DO

 !CALL READ_DATA
 !IF(READ_OPER==1)GOTO 10

 !SOLID_X = 5.0_DP/3.0_DP
 !SOLID_Z = 0.0_DP
 
 !SOLID_W = 1.25_DP / CHAR_VELOCITY
 !SOLID_V = 0.0_DP
 !SOLID_U = 0.0_DP
 
 !CALL FIND_SOLID
 
 q0 = 3.0_DP

!$OMP PARALLEL DO PRIVATE(XS,YS,ZS,II,JJ,KK)
DO K = 1, NODE_Z
DO J = 1, NODE_Y
DO I = 1, NODE_X

  U(I,J,K) = 0.0_DP
  V(I,J,K) = 0.0_DP
  W(I,J,K) = 0.0_DP
  P(I,J,K) = 0.0_DP
  VOF(I,J,K) = 0.0_DP

  DO II = 1, UNIT_GRID2
  DO JJ = 1, UNIT_GRID2
  DO KK = 1, UNIT_GRID2
  
    XS = 0.5_DP*(X(I-1)+X(I)) + REAL(II,KIND=DP)*DX/REAL(UNIT_GRID2,KIND=DP)
    YS = 0.5_DP*(Y(J-1)+Y(J)) + REAL(JJ,KIND=DP)*DY/REAL(UNIT_GRID2,KIND=DP) 
    ZS = 0.5_DP*(Z(K-1)+Z(K)) + REAL(KK,KIND=DP)*DZ/REAL(UNIT_GRID2,KIND=DP)

    if( zs<= 0.1876_dp .or. sqrt(xs**2+ys**2+(zs-0.8)**2)<=0.5_dp  )then
       vof(i,j,k) = vof(i,j,k)+1.0
   end if  


  END DO
  END DO
  END DO

  VOF(I,J,K)=VOF(I,J,K)/REAL(UNIT_GRID2**3,KIND=DP)
  
  XS = X(I)
  YS = Y(J)
  ZS = Z(K)
  
 if( zs <= 0.1876_dp )then 	
 	 phi(i,j,k)= -zs+0.1876_dp	
 else if( sqrt(xs**2+ys**2+(zs-0.8)**2)<=0.5_dp )then
 	 phi(i,j,k)= -sqrt(xs**2+ys**2+(zs-0.8)**2)+0.5_dp
 	 w(i,j,k)=-1.0_dp
 else 
	 phi(i,j,k)= MAX(-zs+0.1876_dp,-sqrt(xs**2+ys**2+(zs-0.8)**2)+0.5_dp)
 end if
 
END DO
END DO
END DO
!$OMP END PARALLEL DO

 CALL BC3D(PHI)
 CALL BC3D(VOF)
 CALL BC3D(U)
 CALL BC3D(V)
 CALL BC3D(W)
 
 !CALL LS_REDISTANCE(PHI,0)
 
 CALL PLOT
 CALL AMURHO
 CALL STORE_DATA 
 
 CALL SOLVE_NS
 CALL STORE_DATA
 CALL FIND_MASS

 CALL CPU_START_REC
 
END SUBROUTINE

