SUBROUTINE FIND_MASS()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
IMPLICIT NONE
INTEGER :: I,J,K
CHARACTER(3) :: MET,GRI

 MASS_LS = 0.0_DP
 MASS_VOF = 0.0_DP

 VOL_LS = 0.0_DP
 VOL_VOF = 0.0_DP
 
 CALL HEAVY_F(PHI)
 
 !$OMP PARALLEL DO REDUCTION(+:MASS_LS,MASS_VOF,VOL_LS,VOL_VOF)
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
 
 	 VOL_LS = VOL_LS + HEAVY(I,J,K)
 	 VOL_VOF = VOL_VOF + VOF(I,J,K)
	 
	 MASS_LS = MASS_LS + HEAVY(I,J,K)*(HEAVY(I,J,K) + RATIO_RHO*(1.0-HEAVY(I,J,K)))
	 MASS_VOF = MASS_VOF + VOF(I,J,K)*(VOF(I,J,K) + RATIO_RHO*(1.0-VOF(I,J,K)))
	 
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 EM_LS_A = EM_LS_A + ABS(1.0-VOL_LS/IVOL_LS)*DT/TIME_TO_STOP
 EM_VOF_A = EM_VOF_A + ABS(1.0-VOL_VOF/IVOL_vof)*DT/TIME_TO_STOP
 
 
 IF( REC_MASS==0 )THEN
 	
 	WRITE(MET,'(I3.3)')METHOD_CNT
 	WRITE(GRI,'(I3.3)')GRID_CNT
 
 	IMASS_LS = MASS_LS
 	IMASS_VOF = MASS_VOF
	
	IVOL_LS = VOL_LS
	IVOL_VOF = VOL_VOF
	
	CLOSE(11)
	CLOSE(12)
	
 	!OPEN(UNIT=11,FILE='MASS LOSS_'//Met//'_'//GRI//'_.PLT')
 	!OPEN(UNIT=11,FILE='MASS LOSS_'//MET//'.PLT')
 	OPEN(UNIT=11,FILE='MASS LOSS.PLT')
 	WRITE(11,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '
	
 	!OPEN(UNIT=12,FILE='VOL LOSS_'//Met//'_'//GRI//'_.PLT')
 	!OPEN(UNIT=12,FILE='VOL LOSS_'//MET//'.PLT')
 	OPEN(UNIT=12,FILE='VOL LOSS.PLT')
 	WRITE(12,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '
	
 	REC_MASS = 1

	EM_LS_A  = 0.0_DP
	EM_VOF_A = 0.0_DP
	
 END IF
 
  WRITE(11,*)TIME,(1.0-MASS_LS/IMASS_LS)*100,(1.0-MASS_VOF/IMASS_VOF)*100
  WRITE(12,*)TIME,(1.0-VOL_LS/IVOL_LS)*100,(1.0-VOL_VOF/IVOL_VOF)*100 

END SUBROUTINE
