MODULE PRECISION
IMPLICIT NONE
SAVE
INTEGER,PARAMETER :: DP = SELECTED_REAL_KIND(15)
REAL(DP),PARAMETER :: EPS = 1.0E-12_DP
REAL(DP),PARAMETER :: PI = 3.14159265358979323846264338327950288419_DP
END MODULE PRECISION

MODULE PROBLEM_DEF
USE PRECISION
IMPLICIT NONE
SAVE

REAL(DP),ALLOCATABLE,DIMENSION(:) :: X,Y,Z 

logical :: flag_is_on

INTEGER :: INTERFACE_METHOD, IBM_SOLVER, VEL_BC, ST_FORCE, G_FORCE
INTEGER :: LS_SOLVER
INTEGER :: VOF_SOLVER
INTEGER :: SOLID_MOTION, VELOCITY_INTERPOLATION
INTEGER :: VORTEX_DYNAMICS
INTEGER :: NS_SOLVER

INTEGER :: NODE_X, NODE_Y, NODE_Z, UNIT_GRID, UNIT_GRID2
INTEGER :: ITER, REC_MASS
INTEGER :: PRESS_MAX_IT, READ_OPER, PLOT_INT, METHOD_CNT, GRID_CNT, ITER_CNT

REAL(DP) :: XSTART, XEND, YSTART, YEND, ZSTART, ZEND, XL, YL, ZL
REAL(DP) :: L2_U, L2_V, L2_W, LINF_U, LINF_V, LINF_W, LINF_P, DIV, TOL_P, TOL_M, CG_ERROR
REAL(DP) :: DX,DY,DZ,DT,RDT
REAL(DP) :: TIME, TIME_TO_STOP, TIME_TO_PLOT
REAL(DP) :: RATIO_AMU, RATIO_RHO
REAL(DP) :: CHAR_LENGTH, CHAR_VELOCITY, CHAR_TIME
REAL(DP) :: WE, FR, RE
REAL(DP) :: RHO_L,RHO_G,MU_L,MU_G, SURFACE_TENSION,GRAVITY
REAL(DP) :: PRESS_OMEGA, CPU_COST, TS, TE

CHARACTER(20) :: NAME_OF_PROB

END MODULE PROBLEM_DEF

MODULE FLUID_PROPERTIES
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP) :: MASS_wold, mass_vold, mass_uold
REAL(DP) :: MASS_w, mass_v, mass_u
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: U, UH, U_OLD, U_TMP, U1, US, US_OLD, US_TMP
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: V, VH, V_OLD, V_TMP, V1, VS, VS_OLD, VS_TMP
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: W, WH, W_OLD, W_TMP, W1, WS, WS_OLD, WS_TMP
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: RHO, RHO_OLD, AMU, AMU_OLD
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: P, P_OLD, P_OLD2, P_TMP, RHS
END MODULE FLUID_PROPERTIES

MODULE LS_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP) :: INTERFACE_WIDTH
REAL(DP) :: IMASS_LS, MASS_LS, VOL_LS, IVOL_LS, EM_LS, EM_LS_A, EI_LS
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: PHI, PHI_OLD, PHI_TMP, PHI_V, PHI_I
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: NORMAL_X, NORMAL_Y, NORMAL_Z
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: CURV, HEAVY, DELTA, GRAD, SGN
END MODULE LS_DATA

MODULE VOF_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP) :: IMASS_VOF, MASS_VOF, VOL_VOF, IVOL_VOF, EM_VOF, EM_VOF_A, EI_VOF
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: VVOF, VOF, VOF_OLD, VOF_I
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: VOF_X, VOF_Y, VOF_Z
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: VOF_SX,VOF_SY,VOF_SZ
END MODULE VOF_DATA

MODULE IBM_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: SOLID_PHI, SOLID_VOF
REAL(DP) :: FORCE_X, FORCE_Y, FORCE_Z, FORCE_X_OLD, FORCE_Y_OLD, FORCE_Z_OLD
REAL(DP) :: TORQUE_X, TORQUE_Y, TORQUE_Z, TORQUE_X_OLD, TORQUE_Y_OLD, TORQUE_Z_OLD
REAL(DP) :: SOLID_X, SOLID_Y, SOLID_Z,  SOLID_X_OLD, SOLID_Y_OLD, SOLID_Z_OLD
REAL(DP) :: SOLID_TX, SOLID_TY, SOLID_TZ, SOLID_TX_OLD, SOLID_TY_OLD, SOLID_TZ_OLD
REAL(DP) :: SOLID_U, SOLID_V, SOLID_W, SOLID_U_OLD, SOLID_V_OLD, SOLID_W_OLD
REAL(DP) :: SOLID_WX, SOLID_WY, SOLID_WZ, SOLID_WX_OLD, SOLID_WY_OLD, SOLID_WZ_OLD
END MODULE IBM_DATA

MODULE DUMMY_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: S0,S1,S2,SS0,SS1,SS2
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: UP,UM,VP,VM,WP,WM
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: A,B,C,F,G,H
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: FP,FM,GP,GM,HP,HM
END MODULE DUMMY_DATA

MODULE VORTEX_DATA
USE PRECISION
IMPLICIT NONE
SAVE
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: LAMB_X, LAMB_Y, LAMB_Z
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: VOR_X, VOR_Y, VOR_Z
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: LAMB_DIV, Q_CRI, Lam2_CRI, Delta_CRI
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: FLEX_PROD, ENTROPY
REAL(DP),ALLOCATABLE,DIMENSION(:,:,:) :: HELICITY
END MODULE
