SUBROUTINE FIND_MASS()
USE PRECISION
USE PROBLEM_DEF
USE LS_DATA
USE VOF_DATA
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J,K
CHARACTER(2) :: MET,GRI
REAL(DP) :: BUB_VOL
REAL(DP) :: X1,X2,Y1,Y2,Z1,Z2,Vol1,Vol2

 CALL CELL_FACE_VELOCITY()

 MASS_LS = 0.0_DP
 MASS_VOF = 0.0_DP

 VOL_LS = 0.0_DP
 VOL_VOF = 0.0_DP

 CALL HEAVY_F(PHI)
 
 
 !$OMP PARALLEL DO REDUCTION(+:MASS_LS,MASS_VOF,VOL_LS,VOL_VOF)
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
 
  VOL_LS = VOL_LS + HEAVY(I,J,K)
  VOL_VOF = VOL_VOF + VOF(I,J,K)
 
  MASS_LS = MASS_LS + HEAVY(I,J,K)*(HEAVY(I,J,K) + RATIO_RHO*(1.0-HEAVY(I,J,K)))
  MASS_VOF = MASS_VOF + VOF(I,J,K)*(VOF(I,J,K) + RATIO_RHO*(1.0-VOF(I,J,K)))

 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 EM_LS_A = EM_LS_A + ABS(1.0-MASS_LS/IMASS_LS)*DT!/TIME_TO_STOP
 EM_VOF_A = EM_VOF_A + ABS(1.0-MASS_VOF/IMASS_vof)*DT!/TIME_TO_STOP

 X1=0.0;X2=0.0
 Y1=0.0;Y2=0.0
 Z1=0.0;Z2=0.0
 Vol1=0.0;Vol2=0.0
  
 !$OMP PARALLEL DO REDUCTION(+:Vol1,Vol2,X1,X2,Y1,Y2,Z1,Z2)
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X 
 
    IF( X(I)>0.0_DP )THEN
        Vol1 = Vol1 + (1.0_DP-HEAVY(I,J,K))
        X1 = X1 + X(I)*(1.0_DP-HEAVY(I,J,K))
        Y1 = Y1 + Y(J)*(1.0_DP-HEAVY(I,J,K))
        Z1 = Z1 + Z(K)*(1.0_DP-HEAVY(I,J,K))
    ELSE
        Vol2 = Vol2 + (1.0_DP-HEAVY(I,J,K))
        X2 = X2 + X(I)*(1.0_DP-HEAVY(I,J,K))
        Y2 = Y2 + Y(J)*(1.0_DP-HEAVY(I,J,K))
        Z2 = Z2 + Z(K)*(1.0_DP-HEAVY(I,J,K))
    ENDIF
 
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO
 
 X1=X1/Vol1;X2=X2/Vol2
 Y1=Y1/Vol1;Y2=Y2/Vol2
 Z1=Z1/Vol1;Z2=Z2/Vol2
 
 IF( REC_MASS==0 )THEN
 
   WRITE(MET,'(I2.2)')ITER_CNT
   WRITE(GRI,'(I2.2)')GRID_CNT
 
   IMASS_LS = MASS_LS
   IMASS_VOF = MASS_VOF

   IVOL_LS = VOL_LS
   IVOL_VOF = VOL_VOF 

   !CLOSE(11)
   CLOSE(12)

   !OPEN(UNIT=11,FILE='MASS LOSS_'//Met//'_'//GRI//'_.PLT')
   !OPEN(UNIT=11,FILE='MASS LOSS_'//GRI//'.PLT')
   OPEN(UNIT=11,FILE='MASS LOSS.PLT')
   WRITE(11,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '

   !OPEN(UNIT=12,FILE='VOL LOSS_'//Met//'_'//GRI//'_.PLT')
   !OPEN(UNIT=12,FILE='VOL LOSS_'//GRI//'.PLT')
   OPEN(UNIT=12,FILE='VOL LOSS.PLT')
   WRITE(12,*)'VARIABLES = "T" "LOSS OF LS(%)" "LOSS OF VOF(%)" '

   !OPEN(UNIT=12,FILE='MassVolLoss_'//GRI//'_.PLT')
   !OPEN(UNIT=12,FILE='MassVolLoss.PLT')
   !OPEN(UNIT=12,FILE='MassVolLoss'//MET//'_'//GRI//'.PLT')
   !WRITE(12,*)'VARIABLES = "T", "LOSS OF VOL(%)", "LOSS OF MASS(%)"'
   
   !OPEN(UNIT=11,FILE='Position_'//GRI//'_.PLT')
   !OPEN(UNIT=13,FILE='Position_1.PLT')
   !WRITE(13,*)'VARIABLES = "T", "X", "Y" "Z" '
   
   !OPEN(UNIT=14,FILE='Position_2.PLT')
   !WRITE(14,*)'VARIABLES = "T", "X", "Y" "Z" '

   REC_MASS = 1

   EM_LS_A  = 0.0_DP
   EM_VOF_A = 0.0_DP

 END IF
 
  WRITE(11,*)TIME,(1.0-MASS_LS/IMASS_LS)*100,(1.0-MASS_VOF/IMASS_VOF)*100
  WRITE(12,*)TIME,(1.0-VOL_LS/IVOL_LS)*100,(1.0-VOL_VOF/IVOL_VOF)*100 

  !WRITE(12,*)TIME,(1.0-VOL_LS/IVOL_LS)*100, (1.0-MASS_LS/IMASS_LS)*100
  !WRITE(13,*)TIME,X1,Y1,Z1
  !WRITE(14,*)TIME,X2,Y2,Z2
  
END SUBROUTINE
