SUBROUTINE FPC_PROJ_SOLVER()
IMPLICIT NONE

  CALL Adams_Bashforth
  CALL RHS_FPC
  !CALL POISSON_SOLVER
  CALL POISSON_CG_SOLVER
  CALL FPC_MOMENTUM_SOLVER
  
END SUBROUTINE

SUBROUTINE P_ESTIMATE()
USE PRECISION
USE FLUID_PROPERTIES, ONLY : P_TMP, P_OLD, P_OLD2
IMPLICIT NONE
INTEGER :: I,J,K

 !$OMP PARALLEL DO 
 DO K = -2, NODE_Z+3
 DO J = -2, NODE_Y+3
 DO I = -2, NODE_X+3
   P_TMP(I,J,K) = 2.0*P_OLD(I,J,K) - P_OLD2(I,J,K)
   IF(ITER<3)THEN
     P_TMP(I,J,K) = P_OLD(I,J,K)
   ENDIF
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO 
 
 CALL BC3D(P_TMP)
 
END SUBROUTINE

SUBROUTINE RHS_FPC()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
USE DUMMY_DATA, ONLY : F,G,H
IMPLICIT NONE
INTEGER :: I,J,K
REAL(DP) :: CFX,CFY,CFZ
  
 CALL P_ESTIMATE()
 
 !$OMP PARALLEL DO PRIVATE(CFx,CFy,CFz) 
 DO K = 0, NODE_Z
 DO J = 0, NODE_Y
 DO I = 0, NODE_X 
   CFx = ( 1.0 - 2.0*RATIO_RHO/(RHO(I,J,K)+RHO(I+1,J,K)) )
   CFy = ( 1.0 - 2.0*RATIO_RHO/(RHO(I,J,K)+RHO(I,J+1,K)) )
   CFZ = ( 1.0 - 2.0*RATIO_RHO/(RHO(I,J,K)+RHO(I,J,K+1)) )
 
   F(I,J,K) = CFx*(P_TMP(I+1,J,K)-P_TMP(I,J,K))/DX
   G(I,J,K) = CFy*(P_TMP(I,J+1,K)-P_TMP(I,J,K))/DX
   H(I,J,K) = CFz*(P_TMP(I,J,K+1)-P_TMP(I,J,K))/DX
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO 
 
 CALL GS_RHSP()
 
 !$OMP PARALLEL DO 
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   RHS(I,J,K) = RATIO_RHO*RHS(I,J,K) + (F(I,J,K)-F(I-1,J,K))/DX &
   	                                 + (G(I,J,K)-G(I,J-1,K))/DY &
									                   + (H(I,J,K)-H(I,J,K-1))/DZ
 ENDDO
 ENDDO
 ENDDO
 !$OMP END PARALLEL DO 

END SUBROUTINE

SUBROUTINE FPC_MOMENTUM_SOLVER()
USE PRECISION
USE PROBLEM_DEF
USE FLUID_PROPERTIES
IMPLICIT NONE
INTEGER :: I,J,K

 CALL P_ESTIMATE()
 
 !$OMP PARALLEL DO 
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y
 DO I = 1, NODE_X-1
   U1(I,J,K)=  - U1(I,J,K) - (P(I+1,J,K)-P(I,J,K))/(DX*RATIO_RHO) &
               - (2.0_DP/(RHO(I+1,J,K)+RHO(I,J,K))-1.0/RATIO_RHO)*(P_TMP(I+1,J,K)-P_TMP(I,J,K))/DX
   U1(I,J,K)=  U_OLD(I,J,K)+U1(I,J,K)*DT
   U(i,j,k) =  U1(i,j,k)
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO 

 !$OMP PARALLEL DO 
 DO K = 1, NODE_Z
 DO J = 1, NODE_Y-1
 DO I = 1, NODE_X
   V1(I,J,K)=  - V1(I,J,K) - (P(I,J+1,K)-P(I,J,K))/(DY*RATIO_RHO) &
               - (2.0_DP/(RHO(I,J+1,K)+RHO(I,J,K))-1.0/RATIO_RHO)*(P_TMP(I,J+1,K)-P_TMP(I,J,K))/DY
   V1(I,J,K)=  V_OLD(I,J,K)+V1(I,J,K)*DT
   V(i,j,k) =  V1(i,j,k)
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO 

 !$OMP PARALLEL DO 
 DO K = 1, NODE_Z-1
 DO J = 1, NODE_Y
 DO I = 1, NODE_X
   W1(I,J,K)=  - W1(I,J,K) - (P(I,J,K+1)-P(I,J,K))/(DZ*RATIO_RHO) &
               - (2.0_DP/(RHO(I,J,K+1)+RHO(I,J,K))-1.0/RATIO_RHO)*(P_TMP(I,J,K+1)-P_TMP(I,J,K))/DZ
   W1(I,J,K)=  W_OLD(I,J,K)+W1(I,J,K)*DT
   W(i,j,k) =  W1(i,j,k)
 END DO
 END DO
 END DO
 !$OMP END PARALLEL DO 
 
END SUBROUTINE